wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725319142
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.11.8
      5: 0.17.7
      6: 4.41.0
      8:
      - 1
      - 5
      13: darwin-arm64
